import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-background-light dark:bg-background-dark font-display"
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
