import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from 'sonner';
import Header from "./components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className="bg-background-light dark:bg-background-dark font-display text-foreground-light dark:text-foreground-dark"
        suppressHydrationWarning={true}
      >
      <Header />
      <main>
        {children}
      </main>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}